# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {}

modules = []

doc_url = "https://shunxinyi2021.github.io/jubmonbdev/"

git_url = "https://github.com/shunxinyi2021/jubmonbdev/tree/master/"

def custom_doc_links(name): return None
